yoyogo:
  application:
    name: yoyogo_grpc_clientdemo    # go build grpc-demo/client --profile=test
    metadata: "grpc client demo"
    server:
      type: "console"
  cloud:
    discovery:
      cache:
        ttl: 30     # seconds
      register-enable: false
      type: "nacos"
      metadata:
        url: "47.100.213.49"
        port: 8848
        namespace: "public"
        group: ""
        cluster: ""
        auth:
          enable: false
          username: "nacos"
          password: "P@ssW0rd"