apiVersion: v1
kind: Service
metadata:
  name: yuanbootdemo
  labels:
    app: yuanbootdemo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880
      protocol: TCP
  selector:
    app: yuanbootdemo
status:
  loadBalancer:
    ingress:
      - hostname: localhost

